function report = ValidateSolution(r,reference,corridors)
% Independent check at the 101 configuration points. No swept-path checking.
global params_
p=params_; q=p.vehicle; dt=r.tf/p.opti.nfe; i=1:p.opti.nfe;
residual=[diff(r.x)-dt*r.v(i).*cos(r.theta(i));diff(r.y)-dt*r.v(i).*sin(r.theta(i)); ...
    diff(r.theta)-dt*r.v(i).*tan(r.phy(i))/q.lw;diff(r.v)-dt*r.a(i);diff(r.phy)-dt*r.w(i); ...
    r.xr-r.x-q.r2p*cos(r.theta); r.yr-r.y-q.r2p*sin(r.theta); ...
    r.xf-r.x-q.f2p*cos(r.theta); r.yf-r.y-q.f2p*sin(r.theta)];
report.max_equation_residual=max(abs(residual));
boundary=[p.scenario.start;p.scenario.goal];
theta_error=r.theta([1,end])-boundary(:,3);
endpoint=[r.x([1,end])-boundary(:,1);r.y([1,end])-boundary(:,2); ...
    atan2(sin(theta_error),cos(theta_error));r.v([1,end]);r.a([1,end]);r.phy([1,end]);r.w([1,end])];
report.max_endpoint_residual=max(abs(endpoint));
limits=q.phymax*ones(size(r.v)); limits(reference.direction<0)=q.gamma*q.phymax;
viol=[r.v-q.vmax;q.vmin-r.v;abs(r.a)-q.amax;abs(r.w)-q.wmax;abs(r.phy)-limits; ...
    -reference.direction.*r.v;abs(r.x-reference.x)-p.opti.beta;abs(r.y-reference.y)-p.opti.beta; ...
    corridors(:,1,1)-r.xr;r.xr-corridors(:,2,1);corridors(:,3,1)-r.yr;r.yr-corridors(:,4,1); ...
    corridors(:,1,2)-r.xf;r.xf-corridors(:,2,2);corridors(:,3,2)-r.yf;r.yf-corridors(:,4,2)];
report.max_bound_violation=max([0;viol]);
[~,report.minimum_disc_clearance]=CheckPoseCollision([r.x,r.y,r.theta]);
report.cost=EvaluateTrajectoryCost(r); report.reference_cost=EvaluateTrajectoryCost(reference);
report.minimum_segment_length=min(report.cost.segment_lengths);
report.gear_pattern_preserved=report.cost.gear_shifts==report.reference_cost.gear_shifts;
tol=p.opti.validation_tolerance;
report.passed=report.max_equation_residual<=tol && report.max_endpoint_residual<=tol && ...
    report.max_bound_violation<=tol && report.minimum_disc_clearance>=-tol && ...
    report.minimum_segment_length>=p.opti.min_cusp_distance-tol && report.gear_pattern_preserved;
fprintf('T = %.6f s; targeted NLP objective = %.6f; full J = %.6f\n',r.tf,report.cost.target,report.cost.total);
fprintf('Gear shifts = %d; minimum gear segment = %.3f m; disc clearance = %.6f m\n', ...
    report.cost.gear_shifts,report.minimum_segment_length,report.minimum_disc_clearance);
fprintf('Max equation residual = %.3g; bound violation = %.3g; endpoint residual = %.3g\n', ...
    report.max_equation_residual,report.max_bound_violation,report.max_endpoint_residual);
assert(report.passed,'CMINLP:Validation','The computed solution failed the independent configuration-point checks.');
end
